### ISSUE TITLE
Failure obtaining authorization

### ISSUE THREAD

**Issue by nauj27** [rycus86/TweetWear#35]
![Screenshot_20190524-090822](https://user-images.githubusercontent.com/2448/58309097-869dc900-7e03-11e9-88a8-1be2946b6f6e.jpg)

In the main app, when I touch "Ingrese en su cuenta" a toast is shown with: "Fallo al obtener la autorización".

**Comment by rycus86** [comment]
Hi! I have not touched this app in a while so it's possible something has changed in the Twitter API that is breaking now. :/
Any chance you could get logs from ADB for example to see if there's any indication there about what's going wrong?
Thanks!

**Comment by nauj27** [comment]
Sure, here you are:

```
2019-05-28 07:51:33.663 32642-5443/? E/AuthorizationTask: Failed to request authorization
    org.scribe.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: '<?xml version="1.0" encoding="UTF-8"?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>'
        at org.scribe.extractors.TokenExtractorImpl.extract(TokenExtractorImpl.java:41)
        at org.scribe.extractors.TokenExtractorImpl.extract(TokenExtractorImpl.java:27)
        at org.scribe.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:64)
        at org.scribe.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:40)
        at org.scribe.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:45)
        at hu.rycus.tweetwear.twitter.async.AuthorizationTask.doInBackground(AuthorizationTask.java:30)
        at hu.rycus.tweetwear.twitter.async.AuthorizationTask.doInBackground(AuthorizationTask.java:15)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by rycus86** [comment]
Thanks @nauj27 !
I think there was a change in the Twitter API to validate callback URLs. I changed it slightly now, not sure if that was enough. Could you please try it again?

Thank you!

**Comment by nauj27** [comment]
Should I install some other version? Where can I get it, if it is necessary? Currently I got the same error with same version.

**Comment by rycus86** [comment]
Oh OK, I'd probably need some code changes then and re-release the app.
I'll try to see if I can get it done in the near future - I don't currently have the Android dev tools installed and configured. :/

**Comment by rycus86** [comment]
OK, I did have to change the OAuth callback URL - https://developer.twitter.com/en/docs/basics/apps/guides/callback-urls.html

I have pushed a new version of the app to the Play Store, hopefully should hit it in a few minutes/hours.
If you get a chance, please tell me if it worked or not. Thanks a lot!
